#!/usr/bin/env bash

# Create the irbrc for the currently selected ruby installation.
__rvm_irbrc()
{
  if [[ -d "$rvm_ruby_home" && ! -s "$rvm_ruby_irbrc" ]] ; then
    \cp "$rvm_scripts_path/irbrc" "$rvm_ruby_irbrc"
  fi
  return $?
}

