#!/usr/bin/env bash
set -e

TMP_PATH="/tmp/rbenv_use.tmp"

root="$(pwd)"
while [ -n "$root" ]; do
  if [ -e "${root}/.rbenv-version" ]; then
    echo "${root}/.rbenv-version"
    exit
  fi
  root="${root%/*}"
done

GLOBAL_PATH="${HOME}/.rbenv/global"
DEFAULT_PATH="${HOME}/.rbenv/default"

if [ -e "$TMP_PATH" ]; then
  echo "$TMP_PATH"
elif [ -e "$GLOBAL_PATH" ]; then
  echo "$GLOBAL_PATH"
elif [ -e "$DEFAULT_PATH" ]; then
  echo "$DEFAULT_PATH"
else
  echo "$GLOBAL_PATH"
fi
