#!/usr/bin/env bash
#
# Summary: Find the file that specifies the current ruby version
#
# Finds the file in which the ruby version that applies to the current context
# is kept. The following locations are tried, in order:
#
# - local file in the location of the ruby script being run
# - local file in the current location
# - global file at $RBENV_ROOT/version
# - global file at $RBENV_ROOT/global
# - global file at $RBENV_ROOT/default
#
# If none exist, the command displays "$RBENV_ROOT/version".

set -e
[ -n "$RBENV_DEBUG" ] && set -x

if rbenv-local-version-file "$RBENV_DIR"; then
  exit
elif [ "$RBENV_DIR" != "$PWD" ] && rbenv-local-version-file "$PWD"; then
  exit
fi

global_version_file="${RBENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${RBENV_ROOT}/global" ]; then
  echo "${RBENV_ROOT}/global"
elif [ -e "${RBENV_ROOT}/default" ]; then
  echo "${RBENV_ROOT}/default"
else
  echo "$global_version_file"
fi
