#!/usr/bin/env bash
set -e

GLOBAL_PATH="${HOME}/.rbenv/global"

if [ -z "$RBENV_VERSION" ]; then
  RBENV_VERSION_FILE="$(rbenv-version-file)"
  
  if [ -e "$RBENV_VERSION_FILE" ]; then
    RBENV_VERSION="$(rbenv-version-file-read "$RBENV_VERSION_FILE" || true)"
  elif [ "$RBENV_VERSION_FILE" = "$GLOBAL_PATH" ]; then
  	# Missing global file is equivalent to 'system'
  	RBENV_VERSION="system"
  fi
fi

if [ "$RBENV_VERSION" = "system" ]; then
  echo "$RBENV_VERSION"
  exit
fi

RBENV_VERSION_PATH="${HOME}/.rbenv/versions/${RBENV_VERSION}"

if [ -d "$RBENV_VERSION_PATH" ]; then
  echo "$RBENV_VERSION"
else
  echo "rbenv: version \`$RBENV_VERSION' is not installed" >&2
  exit 1
fi
