#!/usr/bin/env bash
set -e

TMP_PATH="/tmp/rbenv_use.tmp"
TMP_PATH_FOR_LOCAL="/tmp/rbenv_use_in_local_context.tmp"
GLOBAL_PATH="${HOME}/.rbenv/global"
DEFAULT_PATH="${HOME}/.rbenv/default"

root="$(pwd)"
while [ -n "$root" ]; do
  rbenv_version_path="${root}/.rbenv-version"

  if [ -e "$rbenv_version_path" ]; then
    if [ -e "$TMP_PATH" ]; then
      rm -f "$TMP_PATH"
      echo "$rbenv_version_path"
    elif [ -e "$TMP_PATH_FOR_LOCAL" ]; then
      echo "$TMP_PATH_FOR_LOCAL"
    else
      echo "$rbenv_version_path"
    fi
    exit
  else
    if [ -e "$TMP_PATH_FOR_LOCAL" ]; then
      rm -f "$TMP_PATH_FOR_LOCAL"
    fi
  fi
  root="${root%/*}"
done

if [ -e "$TMP_PATH" ]; then
  echo "$TMP_PATH"
elif [ -e "$GLOBAL_PATH" ]; then
  echo "$GLOBAL_PATH"
elif [ -e "$DEFAULT_PATH" ]; then
  echo "$DEFAULT_PATH"
else
  echo "$GLOBAL_PATH"
fi
