#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

bare=0

if [ "$1" = "--bare" ]; then
	bare=1
	shift
fi

eval "$(rbenv init -)"

original_version=$(rbenv shell 2>/dev/null)

cleanup() {
	if [ -n "$original_version" ]; then
		rbenv shell $original_version
	else
		rbenv shell --unset
	fi
}
trap cleanup 0

for v in $(rbenv versions --bare); do
	if [ "$bare" != "1" ]; then
		echo "$v>> $*" 1>&2
	fi
	rbenv shell $v
	$*
	echo
done

