#!/usr/bin/env bash
# Summary: Show the current Ruby version
set -e
[ -n "$RBENV_DEBUG" ] && set -x

if [ -z "$RBENV_VERSION" ]; then
  RBENV_VERSION_FILE="$(rbenv-version-file)"
  RBENV_VERSION="$(rbenv-version-file-read "$RBENV_VERSION_FILE" || true)"
fi

if [ -z "$RBENV_VERSION" ] || [ "$RBENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${RBENV_ROOT}/versions/${version}" ]
}

if version_exists "$RBENV_VERSION"; then
  echo "$RBENV_VERSION"
elif version_exists "${RBENV_VERSION#ruby-}"; then
  { echo "warning: ignoring extraneous \`ruby-' prefix in version \`${RBENV_VERSION}'"
    echo "         (set by $(rbenv-version-origin))"
  } >&2
  echo "${RBENV_VERSION#ruby-}"
else
  if [ -d "${RBENV_ROOT}/versions" ]; then
    chosen_version="$(ls ${RBENV_ROOT}/versions | grep -e ${RBENV_VERSION} | tail -n 1)"
    if [ -n "${chosen_version}" ] && [ -d ${RBENV_ROOT}/versions/${chosen_version} ]; then
      { echo "warning: ambiguous ruby version \`${RBENV_VERSION}', using \`${chosen_version}'"
      } >&2
      echo "${chosen_version}"
      exit
    fi
  fi

  echo "rbenv: version \`$RBENV_VERSION' is not installed" >&2
  exit 1
fi
