#!/usr/bin/env bash
# Summary: Updates the ruby versions by pulling them from remote
#
# Updates all ruby versions, by cding to the rbenv/plugins directory
# and doing a git pull origin master

set -e
[ -n "$RBENV_DEBUG" ] && set -x

SCRIPT=$(readlink -f $0)
SCRIPTPATH=`dirname $SCRIPT`

cd $SCRIPTPATH/../plugins/ruby-build && git pull origin master

rbenv rehash
