#!/usr/bin/env bash
#/ usage: rbenv usage [--short] <path>
#/
#/ Prints usage of a path.

set -e

if [ "$1" = '--short' ]; then
  grep '^#/' <"$2" | head -1 | cut -c4- >&2
  exit 1
fi

grep '^#/' <"$1" | cut -c4- >&2

plugin="$(basename $1)"
case "$plugin" in "rbenv-global" | "rbenv-local" | "rbenv-sh-shell" )

  print_set_version() {
    echo "<version> should be a string matching a Ruby version known by rbenv."

    local versions="$(rbenv-versions --bare)"
    if [ -z "$versions" ]; then
      echo "There are currently no Ruby versions installed for rbenv."
    else
      echo "The currently installed Ruby versions are:"
      echo "$versions" | sed 's/^/  /'
    fi

    echo
    echo "The special version string 'system' will use your default system Ruby."
  }
  echo
  print_set_version
esac

exit 1
