#!/usr/bin/env bash
#/ usage: rbenv shell [--unset] <version>
#/
#/ Sets a shell-specific Ruby version by setting the 'RBENV_VERSION'
#/ environment variable in your shell. This version overrides both
#/ project-specific versions and the global version.

set -e
[ -n "$RBENV_DEBUG" ] && set -x

# Provide rbenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec rbenv-versions --bare
fi

version="$1"

if [ -z "$version" ]; then
  if [ -z "$RBENV_VERSION" ]; then
    echo "rbenv: no shell-specific version configured" >&2
    exit 1
  else
    echo "echo \"\$RBENV_VERSION\""
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  echo "unset RBENV_VERSION"
  exit 1
fi

# Make sure the specified version is installed.
rbenv-prefix "$version" >/dev/null

echo "export RBENV_VERSION=\"${version}\""
