#!/usr/bin/env bash
# Summary: Show the current Ruby version and its origin
#
# Shows the currently selected Ruby version and how it was
# selected. To obtain only the version string, use `rbenv
# version-name'.

set -e
[ -n "$RBENV_DEBUG" ] && set -x

version_origin=$(rbenv-version-origin)
if [[ -z $version_origin ]]; then
  echo "$(rbenv-version-name)"' (set the global version with: `rbenv global VERSION`)'
else
  echo "$(rbenv-version-name) (set by $version_origin)"
fi
