#!/usr/bin/env bash
#/ usage: rbenv help <command>
#/
#/ Prints general help or command help.

set -e
[ -n "$RBENV_DEBUG" ] && set -x


case "$1" in
"") echo "usage: rbenv <command> [<args>]

Some useful rbenv commands are:
   commands      List all rbenv commands
   rehash        Rehash rbenv shims (run this after installing binaries)
   global        Set or show the global Ruby version
   local         Set or show the local directory-specific Ruby version
   shell         Set or show the shell-specific Ruby version
   version       Show the current Ruby version
   versions      List all Ruby versions known by rbenv
   which         Show the full path for the given Ruby command
   whence        List all Ruby versions with the given command

See 'rbenv help <command>' for information on a specific command.
For full documentation, see: https://github.com/sstephenson/rbenv#readme"
;;
*)
  command_path="$(command -v "rbenv-$1" || true)"
  if [ -n "$command_path" ]; then
    exec rbenv-usage "$command_path"
  else
    echo "rbenv: no such command \`$1'"
  fi
esac
