#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Ruby version
#
# Usage: rbenv exec [--ruby VERSION] <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Ruby
# version's `bin' directory is at the front.
#
# For example, if the currently selected Ruby version is 1.9.3-p327:
#   rbenv exec bundle install
#
# is equivalent to:
#   PATH="$RBENV_ROOT/versions/1.9.3-p327/bin:$PATH" bundle install
#
# You may also override the path that would otherwise be selected by
# specifying a Ruby version on which to operate with the --ruby flag.

set -e
[ -n "$RBENV_DEBUG" ] && set -x

# Provide rbenv completions
if [ "$1" = "--complete" ]; then
  exec rbenv shims --short
fi

# Provide ability to specify which Ruby
if [ "$1" = "--ruby" ]; then
  export RBENV_VERSION="$2"
  RBENV_COMMAND="$3"
  shift 2
else
  export RBENV_VERSION="$(rbenv-version-name)"
  RBENV_COMMAND="$1"
fi

if [ -z "$RBENV_COMMAND" ]; then
  rbenv-help --usage exec >&2
  exit 1
fi

RBENV_COMMAND_PATH="$(rbenv-which "$RBENV_COMMAND")"
RBENV_BIN_PATH="${RBENV_COMMAND_PATH%/*}"

for script in $(rbenv-hooks exec); do
  source "$script"
done

shift 1
if [ "$RBENV_VERSION" != "system" ]; then
  export PATH="${RBENV_BIN_PATH}:${PATH}"
fi

exec -a "$RBENV_COMMAND" "$RBENV_COMMAND_PATH" "$@"
