#!/usr/bin/env bash
# Summary: Explain how the current Ruby version is set
set -e
[ -n "$RBENV_DEBUG" ] && set -x

if [ -n "$RBENV_VERSION" ]; then
  echo "RBENV_VERSION environment variable"
else
  version_file=$(rbenv-version-file)
  if [[ -f $version_file ]]; then
    echo $version_file
  fi
fi
