#!/usr/bin/env bash
#/ usage: rbenv set-local <version>
#/
#/ Sets the local directory-specific Ruby version by writing the version
#/ name to a file named '.rbenv-version'.
#/
#/ When you run a Ruby command, rbenv will look for an '.rbenv-version'
#/ file in the current directory and each parent directory. If no such
#/ file is found in the tree, rbenv will use the default Ruby version
#/ specified with `rbenv set-default', or the version specified in the
#/ RBENV_VERSION environment variable.
set -e

usage() {
  grep '^#/' <"$0" | cut -c4- >&2
  exit 1
}

expr -- "$*" : ".*--help" >/dev/null && usage

RBENV_VERSION="$1"
if [ -z "$RBENV_VERSION" ]; then
  usage
fi

# Make sure the specified version is installed
rbenv-prefix "$RBENV_VERSION" >/dev/null

echo "$RBENV_VERSION" > .rbenv-version
