#!/usr/bin/env bash
set -e
[ -n "$RBENV_DEBUG" ] && set -x

RBENV_VERSION_NAME="$(rbenv-version-name)"

if [ "$1" = "--bare" ]; then
  hit_prefix=""
  miss_prefix=""
  print_version="$RBENV_VERSION_NAME"
else
  hit_prefix="* "
  miss_prefix="  "
  print_version="$(rbenv-version)"
fi

print_version_line() {
  version=$1

  if [ "$version" == "$RBENV_VERSION_NAME" ]; then
    echo "${hit_prefix}${print_version}"
  else
    echo "${miss_prefix}${version}"
  fi
}

# always include system in versions
print_version_line "system"

for path in "${RBENV_ROOT}/versions/"*; do
  if [ -d "$path" ]; then
    print_version_line "${path##*/}"
  fi
done
