#!/usr/bin/env bash
# Summary: Show the current Ruby version and its origin
#
# Shows the currently selected Ruby version and how it was
# selected. To obtain only the version string, use `rbenv
# version-name'.

set -e
[ -n "$RBENV_DEBUG" ] && set -x

cd ../plugins/ruby-build && git pull origin master
rbenv rehash
