#!/usr/bin/env bash

declare rvm_verbose_flag rvm_debug_flag

true ${rvm_verbose_flag:=0} ${rvm_debug_flag:=0} "${rvm_hook:=}"

if [[ -n "$rvm_hook" ]]
then
  if [[ "$PWD/.rvm/hooks/$rvm_hook" = "$rvm_hooks_path/$rvm_hook" ]]
  then
    hooks=( "$rvm_hooks_path/$rvm_hook")
  else
    hooks=("$PWD/.rvm/hooks/$rvm_hook" "$rvm_hooks_path/$rvm_hook")
  fi

  for hook in "${hooks[@]}"
  do
    if [[ -s "$hook" ]]
    then
      if (( rvm_verbose_flag > 0 )) || (( rvm_debug_flag > 0 ))
      then
        rvm_log "Running $hook"
      fi

      source "$hook"
    else
      continue
    fi

  done
fi

unset rvm_hook
