#!/usr/bin/env bash

sys=$( uname -s )
if [[ "${sys}" = AIX ]]
then
  name_opt=-name
else
  name_opt=-iname
fi
original_ruby_version=${rvm_ruby_version:-""}
original_ruby_string=${rvm_ruby_string:-""}

source "$rvm_scripts_path/base"
source "$rvm_scripts_path/patches"
source "$rvm_scripts_path/functions/build"
source "$rvm_scripts_path/functions/pkg"
source "$rvm_scripts_path/functions/irbrc"
source "$rvm_scripts_path/functions/db"
source "$rvm_scripts_path/functions/manage/base"

unset RUBYLIB RUBYOPT # Sanity check.

args=($*)
action="${args[0]:-""}"
rubies_string="${args[1]:-""}"
args="$(echo ${args[@]:2}) " # Strip trailing / leading / extra spacing.
binaries=()

__rvm_manage_rubies  # located in scripts/functions/manage/base

exit $?
