'\" t
.\"     Title: rvm
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 07/16/2010
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "RVM" "1" "07/16/2010" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
rvm \- The Ruby Version Manager
.SH "SYNOPSIS"
.sp
\fBrvm\fR [\fIFLAGS\fR] [\fIOPTIONS\fR] \fIACTION\fR [\fIIMPLEMENTATION\fR[,\fIIMPLEMENTATION\fR[,\fI\&...\fR]]
.SH "DESCRIPTION"
.sp
RVM is a command line tool which allows us to easily install, manage and work with multiple ruby environments from interpreters to sets of gems\&.
.SH "FLAGS"
.PP
\fB\-\-head\fR
.RS 4
with update, updates rvm to git head version\&.
.RE
.PP
\fB\-\-rubygems\fR
.RS 4
with update, updates rubygems for selected ruby
.RE
.PP
\fB\-\-default\fR
.RS 4
with ruby select, sets a default ruby for new shells\&.
.RE
.PP
\fB\-\-debug\fR
.RS 4
Toggle debug mode on for very verbose output\&.
.RE
.PP
\fB\-\-trace\fR
.RS 4
Toggle trace mode on to see EVERYTHING rvm is doing\&.
.RE
.PP
\fB\-\-force\fR
.RS 4
Force install, removes old install & source before install\&.
.RE
.PP
\fB\-\-summary\fR
.RS 4
Used with rubydo to print out a summary of the commands run\&.
.RE
.PP
\fB\-\-latest\fR
.RS 4
with gemset \-\-dump skips version strings for latest gem\&.
.RE
.PP
\fB\-\-gems\fR
.RS 4
with uninstall/remove removes gems with the interpreter\&.
.RE
.PP
\fB\-\-docs\fR
.RS 4
with install, attempt to generate ri after installation\&.
.RE
.PP
\fB\-\-reconfigure\fR
.RS 4
Force \&./configure on install even if Makefile already exists\&.
.RE
.SH "OPTIONS"
.PP
\fB\-v, \-\-version\fR
.RS 4
Emit rvm version loaded for current shell\&.
.RE
.PP
\fB\-l, \-\-level\fR
.RS 4
patch level to use with rvm use / install
.RE
.PP
\fB\-\-prefix\fR
.RS 4
path for all rvm files (\fI~/\&.rvm/\fR), with trailing slash!
.RE
.PP
\fB\-\-bin\fR
.RS 4
path for binaries to be placed (\fI~/\&.rvm/bin/\fR)
.RE
.PP
\fB\-\-source\fR
.RS 4
src directory to use (\fI~/\&.rvm/src/\fR)
.RE
.PP
\fB\-\-archives\fR
.RS 4
directory for downladed files (\fI~/\&.rvm/archives/\fR)
.RE
.PP
\fB\-S\fR
.RS 4
Specify a script file to attempt to load and run (rubydo)\&.
.RE
.PP
\fB\-e\fR
.RS 4
Execute code from the command line\&.
.RE
.PP
\fB\-G\fR
.RS 4
root gem path to use
.RE
.PP
\fB\-\-gems\fR
.RS 4
Used to set the
\fIgems_flag\fR, use with
\fIremove\fR
to remove gems\&.
.RE
.PP
\fB\-\-archive\fR
.RS 4
Used to set the
\fIarchive_flag\fR, use with
\fIremove\fR
to remove archive\&.
.RE
.PP
\fB\-\-patch\fR, \fB\-\-patches\fR
.RS 4
With any ruby build from source, allows you to specify patch paths and patch names to be applied prior to building\&. Values should be a relative / absolute path to a patch or the name of known patch / patchset\&. Optionally, paths or names may be followed by
\fI%someinteger\fR
\- e\&.g\&.
\fI\-\-patches mypatch%2\fR
\- where the number following the % specifies the value of the \-p argument to patch, defaulting to two\&.
.RE
.PP
\fB\-C, \-\-configure\fR
.RS 4
custom configure options\&. If you need to pass several configure options then append them comma separated:
\fI\-C \-\-\&...,\-\-\&...,\-\-\&...\fR\&.
.RE
.PP
\fB\-\-nice\fR
.RS 4
process niceness (for slow computers, default 0)
.RE
.PP
\fB\-\-ree\-options\fR
.RS 4
Options passed directly to ree\(cqs
\fI\&./installer\fR
on the command line\&.
.RE
.SH "ACTIONS"
.PP
\fBusage\fR
.RS 4
Show this usage information\&.
.RE
.PP
\fBversion\fR
.RS 4
Show the rvm version installed in rvm_path\&.
.RE
.PP
\fBuse\fR
.RS 4
Setup current shell to use a specific ruby version\&.
.RE
.PP
\fBreload\fR
.RS 4
Reload rvm source itself (useful after changing rvm source)\&.
.RE
.PP
\fBenv\fR
.RS 4
Displays information about an environment specified but the given ruby string\&. Useful for getting a sourceable path or an evaluatable set of shell variable declarations\&.
.RE
.PP
\fBimplode\fR
.RS 4
(seppuku) removes the rvm installation completely\&. This means everything in $rvm_path (\fI~/\&.rvm\fR)\&. This does not touch your profiles, which is why there is an if around the sourcing
\fIscripts/rvm\fR\&.
.RE
.PP
\fBupdate\fR
.RS 4
Upgrades rvm to the latest version\&. (If you experience bugs try this first with \-\-head)\&.
.RE
.PP
\fBreset\fR
.RS 4
Remove current and stored default & system settings\&. (If you experience odd behavior try this second)\&.
.RE
.PP
\fBinfo\fR
.RS 4
Show the
\fBcurrent\fR
environment information for current ruby\&.
.RE
.PP
\fBdebug\fR
.RS 4
Show info plus additional information for common issues\&.
.RE
.PP
\fBinstall\fR
.RS 4
Install one or many ruby versions\&.
http://rvm\&.beginrescueend\&.com/rubies/installing/
.RE
.PP
\fBuninstall\fR
.RS 4
Uninstall one or many ruby versions, leaves their sources\&.
.RE
.PP
\fBremove\fR
.RS 4
Uninstall one or many ruby versions and remove their sources\&.
.RE
.PP
\fBwrapper\fR
.RS 4
Generates a set of wrapper executables for a given ruby with the specified ruby and gemset combination\&. Used under the hood for passenger support and the like\&.
.RE
.PP
\fBruby\fR
.RS 4
Runs a named ruby file against specified and/or all rubies\&.
.RE
.PP
\fBgem\fR
.RS 4
Runs a gem command using selected ruby\(cqs
\fIgem\fR\&.
.RE
.PP
\fBrake\fR
.RS 4
Runs a rake task against specified and/or all rubies\&.
.RE
.PP
\fBtests\fR
.RS 4
Runs
\fIrake test\fR
across selected ruby versions\&.
.RE
.PP
\fBspecs\fR
.RS 4
Runs
\fIrake spec\fR
across selected ruby versions\&.
.RE
.PP
\fBmonitor\fR
.RS 4
Monitor cwd for testing, run
\fIrake {spec,test}\fR
on changes\&.
.RE
.PP
\fBgemset\fR
.RS 4
gemsets:
http://rvm\&.beginrescueend\&.com/gemsets/
.RE
.PP
\fBgemdir\fR
.RS 4
Display the path to the current gem directory (\fI$GEM_HOME\fR)\&.
.RE
.PP
\fBsrcdir\fR
.RS 4
Display the path to rvm source directory (may be yanked)\&.
.RE
.PP
\fBfetch\fR
.RS 4
Performs an archive / src fetch only of the selected ruby\&.
.RE
.PP
\fBlist\fR
.RS 4
Show currently installed rubies, interactive output\&.
http://rvm\&.beginrescueend\&.com/rubies/list/
.RE
.PP
\fBpackage\fR
.RS 4
Install a dependency package {readline,iconv,zlib,openssl}\&.
http://rvm\&.beginrescueend\&.com/packages/
.RE
.PP
\fBnotes\fR
.RS 4
Display notes, with operating system specifics\&.
.RE
.SH "IMPLEMENTATION"
.PP
\fBruby\fR
.RS 4
MRI/YARV Ruby (The Gold Standard) {1\&.8\&.6,1\&.8\&.7,1\&.9\&.1,1\&.9\&.2\&...}
.RE
.PP
\fBjruby\fR
.RS 4
JRuby, Ruby interpreter on the Java Virtual Machine\&.
.RE
.PP
\fBrbx\fR
.RS 4
Rubinius
.RE
.PP
\fBree\fR
.RS 4
Ruby Enterprise Edition, MRI Ruby with several custom patches for performance, stability, and memory\&.
.RE
.PP
\fBmacruby\fR
.RS 4
MacRuby, insanely fast, can make real apps (Mac OS X Only)\&.
.RE
.PP
\fBmaglev\fR
.RS 4
GemStone Ruby, awesome persistent ruby object store\&.
.RE
.PP
\fBironruby\fR
.RS 4
IronRuby, NOT supported yet\&. Looking for volunteers to help\&.
.RE
.PP
\fBsystem\fR
.RS 4
Use the system ruby (eg\&. pre\-rvm state)\&.
.RE
.PP
\fBdefault\fR
.RS 4
Use rvm set default ruby and system if it hasn\(cqt been set\&.
http://rvm\&.beginrescueend\&.com/rubies/default/
.RE
.SH "RESOURCES"
.sp
Main web site
.sp
Online issue\-tracker
.SH "COPYING"
.sp
Copyright (c) 2009 Wayne E\&. Seguin
.sp
See LICENCE file for details\&.
