name: Release
on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@ccf2332299a883f6af50a1d2d41e5df7904dd769 # v4.1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: rbenv
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
